name: Test Docker Image Creation

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and Publish Docker image in GPR
        uses: saubermacherag/gpr-docker-publish@master
        with:
          IMAGE_NAME: 'gpr-docker-publish-test'
          TAG: 'v0.0'
          DOCKERFILE_PATH: '.github/docker/Dockerfile'
          BUILD_CONTEXT: '.'
      - name: Build and Publish Docker image to Dockerhub instead of GPR
        uses: saubermacherag/gpr-docker-publish@master
        with:
          TAG: 'v0.0'
          DOCKERFILE_PATH: '.github/docker/Dockerfile'
          BUILD_CONTEXT: '.'
          DOCKERHUB_REPOSITORY: 'pinkrobin/gpr-docker-publish-example'
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKERHUB_PAT }}